apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: fastapi-app
  namespace: flux-system
spec:
  interval: 30s
  url: https://github.com/temesgeng92/fastapi-gitops-demo.git 
  ref:
    branch: main
  ignore: |
    /*
    !/kubernetes/
