apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: fastapi-app
  namespace: flux-system
spec:
  interval: 1m                     # Re-apply every 1 minute
  path: ./kubernetes               # Which folder has the manifests
  prune: true                      # Delete if removed from Git
  sourceRef:
    kind: GitRepository
    name: fastapi-app              # Use the GitRepository above
